ProyectoGimnasio/Models/Rol.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGimnasio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rol()
        {
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int IDRol { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> HABILITADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}

ProyectoGimnasio/Models/RolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoGimnasio.Models
{
    public class RolController : Controller
    {
        // GET: Rol
        public ActionResult Index()
        {

            List<RolCLS> listaRol = new List<RolCLS>();
            using (var db = new Entities())
            {
                listaRol = (from rol in db.Rol

                            select new RolCLS
                            {
                                IDRol = rol.IDRol,
                                NOMBRE = rol.NOMBRE,
                                DESCRIPCION = rol.DESCRIPCION,
                                HABILITADO = (int)rol.HABILITADO
                            }).ToList();
            }
            return View(listaRol);

        }


        public ActionResult Filtrar(RolCLS oRolCLS)
        {
            string nombreRol = oRolCLS.nombreFiltro;
            List<RolCLS> listaRol = new List<RolCLS>();
            using (var db = new Entities())
            {
                if (nombreRol == null)
                {
                    listaRol = (from rol in db.Rol
                                select new RolCLS
                                {
                                    IDRol = rol.IDRol,
                                    NOMBRE = rol.NOMBRE,
                                    DESCRIPCION = rol.DESCRIPCION
                                }).ToList();
                }
                else
                {
                    listaRol = (from rol in db.Rol
                                where rol.NOMBRE.Contains(nombreRol)
                                select new RolCLS
                                {
                                    IDRol = rol.IDRol,
                                    NOMBRE = rol.NOMBRE,
                                    DESCRIPCION = rol.DESCRIPCION
                                }).ToList();
                }

            }
            return PartialView("_TablaRol", listaRol);
        }

        public int Guardar(RolCLS oRolCLS, int titulo)
        {
            int respuesta = 0;


            using (var db = new Entities())
            {
                if (titulo == 1)
                {
                    Rol oRol = new Rol();
                    oRol.IDRol = oRolCLS.IDRol;
                    oRol.NOMBRE = oRolCLS.NOMBRE;
                    oRol.DESCRIPCION = oRolCLS.DESCRIPCION;
                    oRol.HABILITADO = 1;
                    db.Rol.Add(oRol);
                    respuesta = db.SaveChanges();
                }
            }
            return respuesta;
        }

        public string Guardar2(RolCLS oRolCLS, int titulo)//Guardar o editar
        {
            string rpta = "";

            try
            {
                if (!ModelState.IsValid)
                {
                    var query = (from state in ModelState.Values
                                 from error in state.Errors
                                 select error.ErrorMessage).ToList();
                    rpta += "<ul class = 'list-group'>";
                    foreach (var item in query)
                    {
                        rpta += "<li class='list-group-item'>" + item + "</li>";
                    }
                    rpta += "</ul>";
                }
                else
                {
                    using (var db = new Entities())
                    {
                        if (titulo == -1)
                        {
                            Rol oRol = new Rol();
                            oRol.IDRol = oRolCLS.IDRol;
                            oRol.NOMBRE = oRolCLS.NOMBRE;
                            oRol.DESCRIPCION = oRolCLS.DESCRIPCION;
                            oRol.HABILITADO = 1;
                            db.Rol.Add(oRol);
                            rpta = db.SaveChanges().ToString();
                            if (rpta == "0") rpta = "";
                        }
                        else
                        {
                            Rol oRol = db.Rol.Where(p => p.IDRol == titulo).First();
                            oRol.NOMBRE = oRolCLS.NOMBRE;
                            oRol.DESCRIPCION = oRolCLS.DESCRIPCION;
                            rpta = db.SaveChanges().ToString();
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                rpta = "";
            }

            return rpta;
        }

        public string Eliminar(RolCLS oRolCLS)
        {
            string respuesta = "";

            try
            {
                int id = oRolCLS.IDRol;
                using (var db = new Entities())
                {
                    Rol oRol = db.Rol.Where(p => p.IDRol == id).First();
                    db.Rol.Remove(oRol);
                    respuesta = db.SaveChanges().ToString();
                }
            }
            catch (Exception)
            {
                respuesta = "";
            }
            return respuesta;
        }

        public JsonResult RellenarCampos(int titulo)
        {
            RolCLS oRolCLS = new RolCLS();
            using (var db = new Entities())
            {
                Rol oRol = db.Rol.Where(p => p.IDRol == titulo).First();
                oRolCLS.NOMBRE = oRol.NOMBRE;
                oRolCLS.DESCRIPCION = oRol.DESCRIPCION;
                oRolCLS.HABILITADO = 1;
            }
            return Json(oRolCLS, JsonRequestBehavior.AllowGet);
        }
    }
}

ProyectoGimnasio/Views/Rol/_TablaRol.cshtml
@model List<ProyectoGimnasio.Models.RolCLS>


<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model[0].IDRol)</th>
            <th>@Html.DisplayNameFor(model => model[0].NOMBRE)</th>
            <th>@Html.DisplayNameFor(model => model[0].DESCRIPCION)</th>
            <th>Operaciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.IDRol)</td>
                <td>@Html.DisplayFor(modelItem => item.NOMBRE)</td>
                <td>@Html.DisplayFor(modelItem => item.DESCRIPCION)</td>
                <td>
                    <button type="button" onclick="Editar(@item.IDRol)" class="btn btn-primary glyphicon glyphicon-edit" data-toggle="modal" data-target="#exampleModal">
                        Editar
                    </button>
                    <button type="button" onclick="Eliminar(@item.IDRol)" class="btn btn-danger glyphicon glyphicon-trash" data-toggle="modal" data-target="#EliminarConfirmacion">
                        Eliminar
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

ProyectoGimnasio/Views/Rol/index.cshtml
@model List<ProyectoGimnasio.Models.RolCLS>
<h2>Perfiles</h2>


<!-- Button trigger modal -->
<button type="button" onclick="Agregar()" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Agregar
</button>

@using (Ajax.BeginForm("Filtrar", "", new AjaxOptions
{
    HttpMethod = "Post",
    UpdateTargetId = "divRol",
    InsertionMode = InsertionMode.Replace
}, new { @id = "frmFiltrado" }))
{
    @Html.Label("Filtrar por Rol")
    @Html.TextBox("nombreFiltro")
    <div id="divRol">
        @Html.Partial("_TablaRol", Model)
    </div>
}


<!-- Modal AGREGAR-->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title" id="exampleModalLabel" align="center" draggable="true"><b>ALTA-MODIFICAR ROL</b></h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @using (Ajax.BeginForm("Guardar2", "Rol", null, new AjaxOptions
            {
                HttpMethod = "POST",
                OnSuccess = "Guardar",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "divError"
            }))
            {
                @Html.Hidden("titulo")
                <div class="modal-body">

                    <div>
                        @Html.Label("Nombre Rol")
                        @Html.TextBox("NOMBRE", null, new { @class = "form-control" })
                    </div>
                    <div>
                        @Html.Label("Descripción")
                        @Html.TextBox("DESCRIPCION", null, new { @class = "form-control" })
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" id="btnclose" class="btn btn-secondary" data-dismiss="modal"><b>Cancelar</b></button>
                    <button type="submit" class="btn btn-primary"><b>GUARDAR</b></button>
                </div>
                <div id="divError" class="alert-warning"></div>
            }
        </div>
    </div>
</div>








<!-- Modal Eliminar -->
<div class="modal fade" id="EliminarConfirmacion" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog " role="document">
        <div class="modal-content">
            <div class="modal-header alert-danger">
                <h2 align="center" class="modal-title" id="exampleModalLabel"><b>Baja de Roles</b></h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <h4 align="center" class="modal-title alert-warning" id="exampleModalLabel"><b>¿Desea eliminar este ROL?</b></h4>
            <div class="modal-footer alert-warning">
                <button type="button" id="btnCerrar" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" onclick="EliminarRegistro()" class="btn btn-primary">Aceptar</button>
            </div>
            <div id="divError"></div>
            }
        </div>
    </div>
</div>


<script>
    var frmFiltrado = document.getElementById("frmFiltrado");
    var nombreFiltro = document.getElementById("nombreFiltro");
    nombreFiltro.onkeyup = function () {
        $("#frmFiltrado").trigger("submit");
    }

    function Agregar() {
        Limpiar();
        document.getElementById("divError").innerHTML = "";
        document.getElementById("titulo").value = "-1";
    }



    function Guardar(resultado) {
        if (resultado == "1" || resultado == "0") {
            $("#frmFiltrado").trigger("submit");
            document.getElementById("btnclose").click();
            alert("Se guardo correctamente");
        } else {
            if (resultado == "-1") {
                alert("Ese Rol ya existe")
                document.getElementById("divError").innerHTML = "";
            } else
                alert("ERROR->No se pudo guardar el Rol");
        }
    }
    function Editar(id) {
        Limpiar();
        document.getElementById("divError").innerHTML = "";
        document.getElementById("titulo").value = id;
        $.get("../Rol/RellenarCampos/?titulo=" + id, function (data) {
            document.getElementById("NOMBRE").value = data.NOMBRE;
            document.getElementById("DESCRIPCION").value = data.DESCRIPCION;
        })
    }



    function Eliminar(IDRol) {
        var id = document.getElementById("titulo").value = IDRol;
    }

    function EliminarRegistro() {
        var id = document.getElementById("titulo").value;
        $.get("../Rol/Eliminar/?IDRol=" + id, function (data) {
            if (data == "1") {
                alert("Rol Eliminado");
                $("#frmFiltrado").trigger("submit");
                document.getElementById("btnCerrar").click();
            }
        })

    }
    function Limpiar() {
        document.getElementById("NOMBRE").value = "";
        document.getElementById("DESCRIPCION").value = "";
        document.getElementById("divError").innerHTML = "";

    }


</script>